Repository aspect-build/bazel-lib, pull requests merged in 2023-02, with the labels that each got.

#357 fix: allow additional attributes to be passed to assert_* tests
  docs/testing.md
  lib/testing.bzl
Labels: enhancement

#366 fix: incorrect 'find -type' argument used on MacOS
  lib/private/write_source_file.bzl
Labels: bug

#371 build: add MacOS and Windows to CI for landed commits
  .aspect/cli/plugins.yaml
  .github/workflows/ci.yaml
Labels: test

#376 chore: depend on skylib release artifact
  BUILD.bazel
  MODULE.bazel
  internal_deps.bzl
Labels: tech debt, deps

#375 Changes needed for rules_js bzlmod support
  docs/docs.md
  e2e/bzlmod/BUILD.bazel
  e2e/bzlmod/MODULE.bazel
  lib/extensions.bzl
  lib/private/docs.bzl
Labels: enhancement

#378 fix: update recommend CI flags from Workflows
  .aspect/bazelrc/ci.bazelrc
  lib/tests/bazelrc_presets/all/ci.bazelrc
Labels: enhancement, cleanup
